# Site
title:              Talaj-Info
bio:                'Talaj-Info Talajvédelmi Szolgáltató Kft.'
description:        "Talajvédelmi terv (hígtrágya-, szennyvíziszap elhelyezés, öntözés, ültetvénytelepítés, végleges más célú hasznosítás, stb.) készítés, tápanyag-gazdálkodási szaktanácsadás elsősorban Baranya, Somogy, és Tolna megyékben"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo_szines_feher_szoveg.svg'
logo_fallback:      'assets/img/logo_szines_feher_szoveg.png'
background:         'assets/img/placeholder-big.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             hu_HU
url:                http://www.talaj-info.hu
#url:                http://127.0.0.1:4000/
email:              talaj-info@talaj-info.hu
phonetel:           +36204347400
phone:              (20) 434-7400
mail:               "7625 Pécs, Gergely u. 15/1."

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
# disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
#email:
twitter:            username
facebook:           username
github:             username
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-redirect-from

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
